# Generated by Django 4.2.16 on 2024-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=10)),
                ('agency_id', models.CharField(max_length=10)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(max_length=100)),
                ('route_desc', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField()),
                ('route_url', models.URLField()),
                ('route_color', models.CharField(max_length=6)),
                ('route_text_color', models.CharField(max_length=6)),
            ],
        ),
    ]
